IGA: limit non-standard strerror_r to glibc after 0add92f4b1eb
POSIX version of strerror_r returns int. musl and FreeBSD libc don't
support the glibc extension while bionic (Android) requires _GNU_SOURCE.

visa/iga/IGALibrary/system.cpp:263:14: error: assigning to 'char *' from incompatible type 'int'
    errMsg = strerror_r(errCode, buf, sizeof(buf));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~