Add missing header for libc++
IGC/OCLFE/igd_fcl_mcl/source/../headers/clang_tb.h:128:30: error: implicit instantiation of undefined template 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >'
    std::vector<std::string> m_Extensions;
                             ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
IGC/OCLFE/igd_fcl_mcl/source/clang_dll.cpp:77:12: error: cannot initialize return object of type 'TC::CTranslationBlock *' with an lvalue of type 'TC::CClangTranslationBlock *'
    return pClangTranslationBlock;
           ^~~~~~~~~~~~~~~~~~~~~~

In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:173:44: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::LiveIntervalsVISA, std::__1::allocator<IGC::DbgDecoder::LiveIntervalsVISA> >'
            std::vector<LiveIntervalsVISA> lrs;
                                           ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:215:44: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::LiveIntervalsVISA, std::__1::allocator<IGC::DbgDecoder::LiveIntervalsVISA> >'
            std::vector<LiveIntervalsVISA> retval;
                                           ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:230:41: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::RegInfoMapping, std::__1::allocator<IGC::DbgDecoder::RegInfoMapping> >'
            std::vector<RegInfoMapping> data;
                                        ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:237:45: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::LiveIntervalGenISA, std::__1::allocator<IGC::DbgDecoder::LiveIntervalGenISA> >'
            std::vector<LiveIntervalGenISA> befp;
                                            ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:239:45: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::LiveIntervalGenISA, std::__1::allocator<IGC::DbgDecoder::LiveIntervalGenISA> >'
            std::vector<LiveIntervalGenISA> callerbefp;
                                            ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:241:45: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::LiveIntervalGenISA, std::__1::allocator<IGC::DbgDecoder::LiveIntervalGenISA> >'
            std::vector<LiveIntervalGenISA> retAddr;
                                            ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:243:46: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::PhyRegSaveInfoPerIP, std::__1::allocator<IGC::DbgDecoder::PhyRegSaveInfoPerIP> >'
            std::vector<PhyRegSaveInfoPerIP> calleeSaveEntry;
                                             ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:245:46: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::PhyRegSaveInfoPerIP, std::__1::allocator<IGC::DbgDecoder::PhyRegSaveInfoPerIP> >'
            std::vector<PhyRegSaveInfoPerIP> callerSaveEntry;
                                             ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:252:64: error: implicit instantiation of undefined template 'std::__1::vector<std::__1::pair<unsigned int, unsigned int>, std::__1::allocator<std::__1::pair<unsigned int, unsigned int> > >'
            std::vector<std::pair<unsigned int, unsigned int>> CISAOffsetMap;
                                                               ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:253:64: error: implicit instantiation of undefined template 'std::__1::vector<std::__1::pair<unsigned int, unsigned int>, std::__1::allocator<std::__1::pair<unsigned int, unsigned int> > >'
            std::vector<std::pair<unsigned int, unsigned int>> CISAIndexMap;
                                                               ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:254:34: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::VarInfo, std::__1::allocator<IGC::DbgDecoder::VarInfo> >'
            std::vector<VarInfo> Vars;
                                 ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:257:41: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::SubroutineInfo, std::__1::allocator<IGC::DbgDecoder::SubroutineInfo> >'
            std::vector<SubroutineInfo> subs;
                                        ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.cpp:36:
In file included from IGC/Compiler/DebugInfo/VISADebugEmitter.hpp:30:
IGC/Compiler/DebugInfo/VISAIDebugEmitter.hpp:261:36: error: implicit instantiation of undefined template 'std::__1::vector<IGC::DbgDecoder::DbgInfoFormat, std::__1::allocator<IGC::DbgDecoder::DbgInfoFormat> >'
        std::vector<DbgInfoFormat> compiledObjs;
                                   ^
/usr/include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^