[VC] Fix `-Wparentheses` for Clang Ubuntu builds
As a follow-up on commit 2109237, address the parentheses warning that's caused
issues within Clang builds:

```
IGC/VectorCompiler/lib/GenXCodeGen/GenXLCECalculation.cpp:257:19: error: using
	the result of an assignment as a condition without parentheses
	[-Werror,-Wparentheses]
  while (NextInst = dyn_cast_or_null<Instruction>(Prev))
         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
IGC/VectorCompiler/lib/GenXCodeGen/GenXLCECalculation.cpp:257:19: note: place
	parentheses around the assignment to silence this warning
  while (NextInst = dyn_cast_or_null<Instruction>(Prev))
                  ^
         (                                             )
```