Add missing header for libc++ after 2117130ce145
In file included from IGC/VectorCompiler/lib/GenXCodeGen/GenXOCLInfoExtractor.cpp:27:
In file included from IGC/VectorCompiler/include/vc/GenXCodeGen/GenXOCLRuntimeInfo.h:28:
IGC/VectorCompiler/include/vc/GenXOpts/Utils/KernelInfo.h:64:10: error: no template named 'unordered_map' in namespace 'std'
    std::unordered_map<Argument *, LinearizedArgInfo>;
    ~~~~~^
IGC/VectorCompiler/include/vc/GenXOpts/Utils/KernelInfo.h:87:3: error: unknown type name 'ArgToImplicitLinearization'
  ArgToImplicitLinearization Linearization;
  ^
IGC/VectorCompiler/include/vc/GenXOpts/Utils/KernelInfo.h:110:30: error: unknown type name 'ArgToImplicitLinearization'
  void updateLinearizationMD(ArgToImplicitLinearization &&Lin);
                             ^